// Claude-powered analysis with deterministic fallbacks. Every function tries
// the Claude API first and falls back to a rule-based heuristic when the API
// is unreachable or no credentials are configured, so the app always works.

import Anthropic from "@anthropic-ai/sdk";

const MODEL = "claude-opus-4-8";

let client = null;
function getClient() {
  if (!client) client = new Anthropic();
  return client;
}

function hasCredentials() {
  return Boolean(
    process.env.ANTHROPIC_API_KEY || process.env.ANTHROPIC_AUTH_TOKEN
  );
}

function firstTextBlock(response) {
  const block = response.content.find((b) => b.type === "text");
  return block ? block.text : "";
}

// ---------------------------------------------------------------------------
// Business model recommendation (founder side)
// ---------------------------------------------------------------------------

export const BUSINESS_MODELS = [
  "saas",
  "marketplace",
  "subscription",
  "ecommerce",
  "freemium",
  "services",
  "advertising",
  "licensing",
];

const RECOMMENDATION_SCHEMA = {
  type: "json_schema",
  schema: {
    type: "object",
    properties: {
      recommendedModel: { type: "string", enum: BUSINESS_MODELS },
      runnerUpModel: { type: "string", enum: BUSINESS_MODELS },
      reasoning: { type: "string" },
      firstSteps: { type: "array", items: { type: "string" } },
      risksToWatch: { type: "array", items: { type: "string" } },
    },
    required: [
      "recommendedModel",
      "runnerUpModel",
      "reasoning",
      "firstSteps",
      "risksToWatch",
    ],
    additionalProperties: false,
  },
};

export async function recommendBusinessModel(answers) {
  if (hasCredentials()) {
    try {
      const response = await getClient().messages.create({
        model: MODEL,
        max_tokens: 16000,
        thinking: { type: "adaptive" },
        system:
          "You are a startup advisor helping young, first-time founders choose " +
          "a business model. Be concrete and encouraging but honest. Ground " +
          "every recommendation in the founder's actual answers, not generic " +
          "advice. First steps should be doable within 30 days with no funding.",
        output_config: { format: RECOMMENDATION_SCHEMA },
        messages: [
          {
            role: "user",
            content:
              "A founder answered a business-model discovery questionnaire. " +
              "Recommend the best business model for them and a runner-up.\n\n" +
              JSON.stringify(answers, null, 2),
          },
        ],
      });
      return { source: "ai", ...JSON.parse(firstTextBlock(response)) };
    } catch (err) {
      console.error("Claude recommendation failed, using heuristic:", err.message);
    }
  }
  return { source: "heuristic", ...heuristicRecommendation(answers) };
}

function heuristicRecommendation(answers) {
  const scores = Object.fromEntries(BUSINESS_MODELS.map((m) => [m, 0]));

  if (answers.offering === "software") {
    scores.saas += 3;
    scores.freemium += 2;
  } else if (answers.offering === "physical") {
    scores.ecommerce += 3;
    scores.subscription += 2;
  } else if (answers.offering === "connecting-people") {
    scores.marketplace += 4;
  } else if (answers.offering === "expertise") {
    scores.services += 3;
    scores.licensing += 1;
  } else if (answers.offering === "content") {
    scores.advertising += 3;
    scores.subscription += 2;
  }

  if (answers.customers === "businesses") {
    scores.saas += 2;
    scores.services += 2;
    scores.licensing += 1;
  } else {
    scores.subscription += 1;
    scores.freemium += 1;
    scores.advertising += 1;
  }

  if (answers.revenuePreference === "recurring") {
    scores.saas += 2;
    scores.subscription += 2;
  } else if (answers.revenuePreference === "per-transaction") {
    scores.marketplace += 2;
    scores.ecommerce += 2;
  }

  if (answers.capital === "little") {
    scores.services += 2;
    scores.saas += 1;
  } else if (answers.capital === "significant") {
    scores.ecommerce += 1;
    scores.marketplace += 1;
  }

  if (answers.technical === "yes") {
    scores.saas += 1;
    scores.freemium += 1;
  } else {
    scores.services += 1;
    scores.ecommerce += 1;
  }

  const ranked = Object.entries(scores).sort((a, b) => b[1] - a[1]);
  const [recommendedModel] = ranked[0];
  const [runnerUpModel] = ranked[1];

  return {
    recommendedModel,
    runnerUpModel,
    reasoning:
      `Based on your answers — offering: ${answers.offering}, customers: ` +
      `${answers.customers}, revenue preference: ${answers.revenuePreference} — ` +
      `a ${recommendedModel} model fits best, with ${runnerUpModel} as a strong ` +
      `alternative. (Generated by the built-in heuristic; connect an Anthropic ` +
      `API key for a personalized AI analysis.)`,
    firstSteps: [
      "Interview 10 potential customers about the problem before building anything",
      "Sketch a one-page landing page describing the offer and collect signups",
      `Price a minimal ${recommendedModel} offer and try to get 3 paying commitments`,
    ],
    risksToWatch: [
      "Building for months without validating anyone will pay",
      "Choosing a model that needs more capital than you can access",
    ],
  };
}

// ---------------------------------------------------------------------------
// Investment analysis (investor side)
// ---------------------------------------------------------------------------

const ANALYSIS_SCHEMA = {
  type: "json_schema",
  schema: {
    type: "object",
    properties: {
      score: { type: "integer", enum: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10] },
      verdict: {
        type: "string",
        enum: ["strong-yes", "worth-a-meeting", "watch", "pass"],
      },
      summary: { type: "string" },
      strengths: { type: "array", items: { type: "string" } },
      risks: { type: "array", items: { type: "string" } },
      questionsForFounder: { type: "array", items: { type: "string" } },
      thesisFit: { type: "string" },
    },
    required: [
      "score",
      "verdict",
      "summary",
      "strengths",
      "risks",
      "questionsForFounder",
      "thesisFit",
    ],
    additionalProperties: false,
  },
};

export async function analyzeInvestment(startup, investor) {
  if (hasCredentials()) {
    try {
      const response = await getClient().messages.create({
        model: MODEL,
        max_tokens: 16000,
        thinking: { type: "adaptive" },
        system:
          "You are an experienced venture analyst writing a first-pass " +
          "investment memo. Be rigorous: weigh traction against stage, flag " +
          "weak metrics plainly, and evaluate fit against the investor's " +
          "stated thesis. A 'strong-yes' should be rare. This memo informs a " +
          "real capital decision, so no hedging and no flattery.",
        output_config: { format: ANALYSIS_SCHEMA },
        messages: [
          {
            role: "user",
            content:
              "Write a first-pass investment analysis.\n\nStartup:\n" +
              JSON.stringify(startup, null, 2) +
              "\n\nInvestor profile:\n" +
              JSON.stringify(
                { name: investor?.name, thesis: investor?.thesis, sectors: investor?.sectors },
                null,
                2
              ),
          },
        ],
      });
      return { source: "ai", ...JSON.parse(firstTextBlock(response)) };
    } catch (err) {
      console.error("Claude analysis failed, using heuristic:", err.message);
    }
  }
  return { source: "heuristic", ...heuristicAnalysis(startup, investor) };
}

function heuristicAnalysis(startup, investor) {
  let score = 5;
  const strengths = [];
  const risks = [];

  if (startup.monthlyRevenue > 10000) {
    score += 2;
    strengths.push(`Meaningful revenue: $${startup.monthlyRevenue.toLocaleString()}/mo`);
  } else if (startup.monthlyRevenue > 0) {
    score += 1;
    strengths.push("Early revenue proves someone will pay");
  } else {
    risks.push("Pre-revenue: willingness to pay is unproven");
  }

  if (startup.monthlyGrowthPct >= 15) {
    score += 2;
    strengths.push(`Strong growth at ${startup.monthlyGrowthPct}% month-over-month`);
  } else if (startup.monthlyGrowthPct >= 5) {
    score += 1;
  } else {
    score -= 1;
    risks.push("Growth is flat for the stage");
  }

  const multiple = startup.askAmount / Math.max(startup.monthlyRevenue * 12, 1);
  if (multiple > 100) {
    score -= 1;
    risks.push("Raise amount is very large relative to current revenue");
  }

  const sectorFit = investor?.sectors?.includes(startup.sector);
  if (sectorFit) {
    score += 1;
  } else if (investor) {
    risks.push(`Sector (${startup.sector}) sits outside the investor's stated focus`);
  }

  score = Math.max(1, Math.min(10, score));
  const verdict =
    score >= 9 ? "strong-yes" : score >= 7 ? "worth-a-meeting" : score >= 5 ? "watch" : "pass";

  return {
    score,
    verdict,
    summary:
      `${startup.name} (${startup.stage}, ${startup.sector}) scores ${score}/10 ` +
      `on traction, growth, and thesis fit. (Generated by the built-in ` +
      `heuristic; connect an Anthropic API key for a full AI memo.)`,
    strengths,
    risks,
    questionsForFounder: [
      "What is churn/retention over the last 3 months?",
      "What does customer acquisition currently cost, and through which channel?",
      "How long does this raise extend the runway, and to what milestone?",
    ],
    thesisFit: sectorFit
      ? "Within the investor's stated sector focus."
      : "Outside the investor's stated sector focus — would need a strong exception case.",
  };
}
